-- down: 20260808045200_drop_legacy_prototype_schema.sql
--
-- ⚠️ 不可逆。移行設計 §5 の「point of no return」に当たる。
--
-- 撤去したのは破棄済みアーキテクチャ（Next.js 期）のスキーマであり、
-- 戻す先の設計そのものが存在しない。復元は意味を持たない。
--
-- 万一、旧スキーマを再現する必要が生じた場合の元ファイル:
--   ブランチ k-okada51/impl-mvp の web/supabase/schema.sql
--   （データは復元できない。適用時点で実データは無かった）

-- 意図的に何もしない。
